name: Build and Deploy site

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - name: Build
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build
    - name: Install SSH Client
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        SSH: true
        BRANCH: gh-pages
        FOLDER: 'dist'
        CLEAN: true
